version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mobrio_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: mobrio_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - rabbitmq
      - redis
  celery:
    build:
      context: ./app
    command: celery -A app.core.celery_worker.celery worker --beat --loglevel=info
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - backend
      - redis
      - rabbitmq
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend


volumes:
  mysql_data:
  rabbitmq_data:
  reddis_data:
